version: 0.1
env:
  variables:
    ROOT_DIR: /var/www/html
phases:
  install:
    commands:
        - echo lets start running nginx
        - apt-get update -y
        - apt-get install nginx -y

    finally:
      - echo check if service running 
  
  build:
    commands:
      - echo start build phase
      - nginx -t 
    finally:
      - echo finish this phase
      - systemctl status nginx
      
  